name: on_push_build_windows_x64
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLUTION_FILE_PATH: umdh-root.pro
  BUILD_CONFIGURATION: Release

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Add AI comment with review for changes
    steps:
      - name: AI review
        uses: actions/ai-code-review@v1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.GITTOKEN }}
          openai_api_key: ${{ secrets.OPENAIAPIKEY }}
          
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.1.2
        setup-python: 'false'
      
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
           
    - name: Build
      env:
        QTDIR: ${{env.Qt5_DIR}}
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: qmake ${{env.SOLUTION_FILE_PATH}} && nmake
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: umdh-gui-windows-x64
        path: ./bin
